spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/accounts?useSSL=false&allowPublicKeyRetrieval=true 
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate: 
      ddl-auto: update
  application:
    name: easyaccounts
  profiles:
    active: dev
  config: 
    import: optional:configserver:http://localhost:8071
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka      
management:
  endpoints:
    web:
       exposure:
         include: "*"
    enabled-by-default: true     
  endpoint:       
    shutdown:
      enabled: true     
  
info:
  app:
    name: EasyAccounts Microservice
    description: Eazy Bank Accounts Application  
    version: 1.0.1
    
    
server:
  port: 7070
  servlet:
    context-path: /accounts
      