spring:
  application:
    name: easyconfigserver
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/muthuism/EasyBank-microservices-config-properties
          clone-on-start: true
        default-label: main 
        bootstrap: false
server:
  port: 8071
    